parameters:
    jonasarts.registry.class: jonasarts\Bundle\RegistryBundle\Services\Registry

services:
    registry:
        class: %jonasarts.registry.class%
        arguments: [ @service_container, @doctrine.orm.entity_manager ]